import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FileUpload from '../components/FileUpload';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resume Improver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Resume Improver!
        </h1>
        <p className={styles.description}>
          Get started by editing uploading your resume in a PDF or DOCX format.
        </p>
        <div>
          <FileUpload />
        </div>
      </main>
    </div>
    
  )
}
